# Generated by Django 5.0.7 on 2024-08-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccountDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email_Id', models.EmailField(blank=True, max_length=50, null=True)),
                ('Password1', models.EmailField(blank=True, max_length=50, null=True)),
                ('Password2', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
