# Generated by Django 5.0.7 on 2024-08-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextWebApp', '0002_createaccountdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createaccountdb',
            old_name='Password1',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='createaccountdb',
            name='Password2',
        ),
    ]
