# Generated by Django 5.0.7 on 2024-08-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextWebApp', '0003_rename_password1_createaccountdb_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createaccountdb',
            name='Username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
