# Generated by Django 5.0.7 on 2024-08-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextWebApp', '0006_orderdb_alter_createaccountdb_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
