# Generated by Django 5.0.7 on 2024-07-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product', models.CharField(blank=True, max_length=50, null=True)),
                ('Pr_Description', models.TextField(blank=True, max_length=5000, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('Pr_Image1', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Pr_Image2', models.ImageField(blank=True, null=True, upload_to='Product Images')),
                ('Pr_Image3', models.ImageField(blank=True, null=True, upload_to='Product Images')),
            ],
        ),
    ]
